### ISSUE TITLE
Edit from GitHub branch does not work

### ISSUE THREAD

**Issue by aleksey-pastuhov** [jgraph/draw.io#82] opened 2017-03-11 08:26 UTC
When I try to edit file from not *master* branch I got next error:

![image](https://cloud.githubusercontent.com/assets/11784219/23821754/c5341ebe-0644-11e7-9133-8ebdb53c179e.png)

Branch: feature/some-text
OS: Linux or Mac (and maybe windows)
Browser: Chrome or Firefox

Here is output in console:
```
GET https://api.github.com/repos/data-stack-org/dev-docs/contents/feature-tree-diagram/diagrams/Feature%20Tree%20Diagram.xml?ref=feature 404 (Not Found)
app.min.js:7929 error in loadFile: data-stack-org/dev-docs/feature/feature-tree-diagram/diagrams/Feature Tree Diagram.xml Object {message: "File not found"}
```

**Comment by aleksey-pastuhov** [comment] 2017-03-11 08:29
Even if I try to create new diagram I got another error:

![image](https://cloud.githubusercontent.com/assets/11784219/23821777/a3364610-0645-11e7-8c7f-2b3fc0e25205.png)

**Comment by aleksey-pastuhov** [comment] 2017-03-11 11:29
Also there is no ability to create/save diagram in custom branch... even without `/` symbol.

![image](https://cloud.githubusercontent.com/assets/11784219/23822886/c536b434-065e-11e7-981e-9784db7c3fdf.png)

**Comment by alderg** [comment] 2017-03-11 12:31
What are the steps to reproduce this last error report (create/save diagram in custom branch)?

**Comment by aleksey-pastuhov** [comment] 2017-03-11 13:03
Steps: 

* Create branch on github
* Open draw.io
* There is modal with github logo and two options create new / open existing
* Choose *create new*
* Select blank diagram
* Click Create
* Select your repository
* Select not *master* branch
* Click OK
* Click OK when commit message appears

Result:
Then you see error 422

**Comment by alderg** [comment] 2017-03-11 13:15
Can't reproduce this one. What filename and branchname did you use?

**Comment by alderg** [comment] 2017-03-11 13:35
Found the problem. Fixing.

**Comment by aleksey-pastuhov** [comment] 2017-03-11 13:45
Great thanks!

**Comment by alderg** [comment] 2017-03-11 14:11
Fixed in 6.3.0. Thanks for the report!

**Closed by alderg** 2017-03-11 14:11 UTC

**Comment by aleksey-pastuhov** [comment] 2017-03-11 14:20
Thanks for your work! Can I get know when 6.3.0 will be published to the users?

**Comment by alderg** [comment] 2017-03-11 14:23
It's in production. Shift-refresh (see Help, About for version).

**Comment by aleksey-pastuhov** [comment] 2017-03-11 14:37
Yeah :) Thanks a lot
