### ISSUE TITLE
gliffy import not working

### ISSUE THREAD

**Issue by christian-korneck** [jgraph/draw.io#29] opened 2016-11-14 12:10 UTC
Hello,

first of all, thanks a lot for the great `draw.io` project!

I've build a `war` file using the supplied `build.xml` and am running it with tomcat. Everything seems to work, except for the `gliffy` import. When I try to import a gliffy file the same way as it works with the cloud instance https://draw.io (either drag and drop of the gliffy file or via File -> Import), it doesn't work. There's no error message either. Dragging and dropping or Importing via the menu of other types of files works as expected.

I'm running draw.io version: `6.0.1.2`

I've also noticed that the gliffy import doesn't work on the github pages demo (same behaviour):
https://jgraph.github.io/draw.io/war/index.html

Are there any additional steps required to activate the gliffy importer?

Thanks,
Christian

**Comment by alderg** [comment] 2016-11-22 10:44
Does the gliffyRegex trigger in the OpenServlet?

**Comment by davidjgraph** [comment] 2017-01-04 21:28
Closing due to lack of reporter response.

**Closed by davidjgraph** 2017-01-04 21:28 UTC

**Comment by christian-korneck** [comment] 2017-01-04 21:30
Do you have a recommended way how to debug this?

**Comment by RTUnit** [comment] 2018-07-21 22:37
### Solution
The issue how I solved was to place **gliffyTranslation.properties** file under **com/mxgraph/io/gliffy/importer/gliffyTranslation**. After that I can drag&drop Gliffy diagram file to draw.io document and it is converted.

### How?
In essence it means copying the file from here:
**.\drawio-8.9.6\src\main\java\com\mxgraph\io\gliffy\importer\gliffyTranslation.properties**
to here:
**.\WEB-INF\classes\com\mxgraph\io\gliffy\importer\gliffyTranslation.properties**
It might be need to restart Tomcat.

### Trace
If you look under Tomcat **%CATALINA_ROOT%\logs\localhost.yyyy-mm-dd.log** this is the error message that was hint to solution:

22-Jul-2018 01:03:02.172 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [OpenServlet] in context with path [/webapp] threw exception [Servlet execution threw an exception] with root cause
 java.util.MissingResourceException: **Can't find bundle for base name com/mxgraph/io/gliffy/importer/gliffyTranslation**, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
	at java.util.ResourceBundle.getBundleImpl(Unknown Source)
	at java.util.ResourceBundle.getBundle(Unknown Source)
	at com.mxgraph.io.gliffy.importer.StencilTranslator.init(Unknown Source)
	at com.mxgraph.io.gliffy.importer.StencilTranslator.<clinit>(Unknown Source)
	at com.mxgraph.io.gliffy.importer.GliffyDiagramConverter.convertGliffyObject(Unknown Source)
	at com.mxgraph.io.gliffy.importer.GliffyDiagramConverter.collectVerticesAndConvert(Unknown Source)
	at com.mxgraph.io.gliffy.importer.GliffyDiagramConverter.start(Unknown Source)
	at com.mxgraph.io.gliffy.importer.GliffyDiagramConverter.<init>(Unknown Source)
	at com.mxgraph.online.OpenServlet.doPost(Unknown Source)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:491)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:764)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1388)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

If this solution does not help then add few System.out.println in OpenServlet.java to see if it gets past statement **if (ENABLE_GLIFFY_SUPPORT && upfile.matches(gliffyRegex))**.
