### ISSUE TITLE
Access to all repositories in GitHub

### ISSUE THREAD

**Issue by dharnitski** [jgraph/draw.io#76] opened 2017-02-28 01:15 UTC
We have big number of private repositories in our organization. Unfortunately, I cannot reach all of them. I see only ~ top 20 without possibility to  scroll or search for the rest.

Thanks for your hard work on this project. I am really amazed how well it is build and how many features are implemented. Great work!

**Comment by alderg** [comment] 2017-02-28 14:20
Duplicate of https://github.com/jgraph/draw.io/issues/75

**Closed by alderg** 2017-02-28 14:20 UTC

**Comment by carlesaraguz** [comment] 2017-07-13 13:00
I kindly think that the issue is not duplicated. @dharnitski was referring to the ability to access repositories owned by a GitHub organization of which one can be part of. I can't see/open my organization-repos either!
